# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-08-16 01:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginAndRegistration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
    ]
